name: GitHub Pages
on:
  # Trigger the workflow on pull request if content in
  # the vuepress folder changes. This merges the changes
  # to the master branch
#  pull_request:
#    types:
#      - closed
  push:
    branches:
      - master
#    paths:
#      - "vuepress/**"

jobs:
  run:
    name: Merge VuePress content to master branch
    runs-on: ubuntu-latest

    steps:
      - name: Checkout master branch
        uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: Generate static content
        run: |
          cd ./vuepress
          npm ci
          npm run build

      # please check out the docs of the workflow for more details
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          verbose: true
          commit_message: "Automated commit to gh-pages branch"
          # deploy to gh-pages branch
          target_branch: gh-pages
          # deploy the default output dir of VuePress
          build_dir: ./vuepress/src/.vuepress/dist
        env:
          # @see https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

#      - name: Commit generated static content
#        uses: EndBug/add-and-commit@v7
#        with:
#          author_name: GitHub Actions
#          author_email: github-actions@github.com
#          branch: master
#          message: "Automated commit."
#          add: ${{ github.workspace }}/docs
#          cwd: './'